export const ACTION_NAMES = [
  "register_sale",
  "register_expense",
  "register_purchase",
  "create_product",
  "edit_product",
  "adjust_stock",
  "deactivate_product",
  "query_today_summary",
  "query_inventory",
  "query_cash",
  "query_report",
  "query_projection",
  "query_recommendations",
  "create_customer",
  "register_credit_sale",
  "register_debt_payment",
  "query_debts",
  "cancel_operation",
  "conversation",
  "unsupported",
];

const nullableString = { type: ["string", "null"] };
const nullableNumber = { type: ["number", "null"] };
const nullableBoolean = { type: ["boolean", "null"] };

export const gemmaInterpretationSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "action",
    "confidence",
    "productId",
    "productName",
    "createProductIfMissing",
    "quantity",
    "unitPrice",
    "paymentMethod",
    "customerId",
    "customerName",
    "amount",
    "expenseCategory",
    "description",
    "purchasePurpose",
    "unitCost",
    "additionalCosts",
    "supplierName",
    "newProductName",
    "productType",
    "purchaseCost",
    "salePrice",
    "tracksStock",
    "currentStock",
    "minimumStock",
    "newStock",
    "reportPeriod",
    "operationId",
    "operationType",
    "responseText",
    "suggestedPrompts",
    "warnings",
  ],
  properties: {
    action: { type: "string", enum: ACTION_NAMES },
    confidence: { type: "number", minimum: 0, maximum: 1 },
    productId: nullableString,
    productName: nullableString,
    createProductIfMissing: { type: "boolean" },
    quantity: nullableNumber,
    unitPrice: nullableNumber,
    paymentMethod: {
      type: ["string", "null"],
      enum: ["cash", "yape", "plin", "credit", null],
    },
    customerId: nullableString,
    customerName: nullableString,
    amount: nullableNumber,
    expenseCategory: {
      type: ["string", "null"],
      enum: [
        "rent",
        "utilities",
        "transport",
        "maintenance",
        "supplier_payment",
        "other",
        null,
      ],
    },
    description: nullableString,
    purchasePurpose: {
      type: ["string", "null"],
      enum: ["merchandise", "internal_supply", "business_expense", null],
    },
    unitCost: nullableNumber,
    additionalCosts: nullableNumber,
    supplierName: nullableString,
    newProductName: nullableString,
    productType: {
      type: ["string", "null"],
      enum: ["product", "service", null],
    },
    purchaseCost: nullableNumber,
    salePrice: nullableNumber,
    tracksStock: nullableBoolean,
    currentStock: nullableNumber,
    minimumStock: nullableNumber,
    newStock: nullableNumber,
    reportPeriod: {
      type: ["string", "null"],
      enum: ["today", "7days", "30days", "all", null],
    },
    operationId: nullableString,
    operationType: {
      type: ["string", "null"],
      enum: ["sale", "expense", "purchase", null],
    },
    responseText: nullableString,
    suggestedPrompts: {
      type: "array",
      maxItems: 4,
      items: { type: "string" },
    },
    warnings: {
      type: "array",
      maxItems: 5,
      items: { type: "string" },
    },
  },
};

export const gemmaClarificationSchema = {
  type: "object",
  additionalProperties: false,
  required: ["kind", "assistantMessage", "action"],
  properties: {
    kind: {
      type: "string",
      enum: ["update", "explain", "cancel"],
    },
    assistantMessage: nullableString,
    action: gemmaInterpretationSchema,
  },
};
